version: '3'
services:
  web:
    image: maintenance-page/latest
    container_name: maintenance-page
    restart: always
    environment:
      - VIRTUAL_HOST=manutencao.flubber.com
networks:
  default:
    external:
      name: nginxproxy_default


