version: '2.2'
services:
  web:
    image: maintenance-page:v2
    container_name: maintenance-page
    cpus: 0.1
    mem_limit: 150m
    mem_reservation: 100m
    restart: always
    environment:
      - VIRTUAL_HOST=manutencao.flubber.com
networks:
  default:
    external:
      name: nginxproxy_default


