apiVersion: skaffold/v2beta19
kind: Config
metadata:
  name: maintenance-page
build:
  artifacts:
  - image: maintenance-page
    docker:
      dockerfile: Dockerfile
deploy:
  kubectl:
    manifests:
    - k8s/configmap.yaml
    - k8s/deployment.yaml
    - k8s/ingress.yaml
    - k8s/pv.yaml
    - k8s/pvc.yaml
    - k8s/secret.yaml
    - k8s/service.yaml
    - k8s/serviceaccount.yaml
