apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc0001
  labels:
    type: local
spec:
  storageClassName: manual
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 800Mi
